import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./_Component/Footer/page";
import Navbar from "./_Component/Navbar/page";
import "@fortawesome/fontawesome-free/css/all.min.css"
import { Toaster } from "_/components/ui/sonner";
// import { SessionProvider } from "next-auth/react";
import MySessionProvider from "./_Component/MysessionProvider/MySessionProvider";
import { Car } from "lucide-react";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MySessionProvider >
          {/* <CartContextProvider> */}

          <Navbar />
          {/* children are the pages or App components such as login, register, home, cart */}
          {children}
          <Toaster />
          <Footer />

          {/* </CartContextProvider> */}
        </MySessionProvider>

      </body>
    </html>
  );
}
